_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: './pretrain_weights/model_retina_dl_pretrain.pth'
  RESNETS:
    DEPTH: 50
    NORM: 'SyncBN'
  RETINANET:
    IOU_THRESHOLDS: [ 0.3, 0.7 ]
  BACKBONE:
    FREEZE_AT: -1
  PIXEL_MEAN: [ 0 ]
  PIXEL_STD: [ 1 ]
DATASETS:
  TRAIN: ("pm_node_v3_submit",)
#  TRAIN: ("pm_node_v3_train",)
  TEST: ("pm_node_v1_submit_test",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
TEST:
  EVAL_PERIOD: 0
INPUT:
  FORMAT: 'L'
#  MIN_SIZE_TRAIN: (768, 896, 1024, 1152, 1280, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
#  MIN_SIZE_TRAIN: (512, 640, 704, 832, 896, 1024, 1152, 1216, 1344, 1408, 1536)
#  MAX_SIZE_TRAIN: 1536
#  MIN_SIZE_TEST: 512
#  MAX_SIZE_TEST: 1536
  RESIZE_SCALE_RANGE_TRAIN: (0.8, 1, 1.2, 1.4, 1.6)
  RESIZE_SCALE_RANGE_TEST: (0.8, 1, 1.2)
  RANDOM_ROTATION_ANGLES: (0, 180)
  GAUSSIAN_BLUR_RANDOM_SIGMA_RANGE: (.1, 3)
  GAUSSIAN_BLUR_KERNEL_SIZE: (5,5)
#  GAUSSIAN_BLUR_RANDOM_SIGMA_RANGE: (0, 0)
  ### windowing notes
  ## dynamic pt-wise quantile image pixel intensity
  WINDOW: (0, 1)
SOLVER:
  IMS_PER_BATCH: 8
  VAL_IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    CLIP_TYPE: "norm"
    NORM_TYPE: 2.0
  STEPS: (19000, 20000)
  MAX_ITER: 21000
  BASE_LR: 0.0005

VIS_PERIOD: 0
OUTPUT_DIR: './detectron2_outputs'